name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
      pages: write # Needed for GitHub Pages deployment
      deployments: write # Needed for GitHub Pages deployment

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install step
        run: "bun install"

      - name: Build step
        run: "bun run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "hisyam99"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "dist"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
